### vars
@cookie = quickship_user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5MzM3MzE4ODczIiwiaWF0IjoxNzM3NjIwMDg5LCJleHAiOjE3MzgzNDAwODl9.FlqLIRhGy1cs0Q7UCF9e7lfI6OOuLFZwZGFx43Oc7iw; Max-Age=604800; Path=/; Expires=Thu, 30 Jan 2025 08:14:49 GMT; HttpOnly; SameSite=Lax


###  signup manager
POST   http://localhost:3000/api/admin/signup
Content-Type: application/json

{
  "name" : "Honey",
  "email": "vhoney@bunny.com",
  "password": "honeybunny"
}

###  login manager
POST   http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "vhoney@bunny.com",
  "password": "honeybunny"
}

###  logout manager
POST     http://localhost:3000/api/admin/logout
Content-Type: application/json

###  get me
GET    http://localhost:3000/api/admin/me
Content-Type: application/json

### create salesman
POST   http://localhost:3000/api/admin/create/salesmen
Content-Type: application/json

{
  "name" : "Honeybunny",
  "userid": "9337318873"
}

### get all salesman
GET   http://localhost:3000/api/admin/get/salesmen/all
Content-Type: application/json

### get my salesman
GET   http://localhost:3000/api/admin/get/salesmen/my
Content-Type: application/json

### create location
POST   http://localhost:3000/api/admin/create/location
Content-Type: application/json

{
  "name" : "SreeLeatherfd",
  "address": "berhampur mandiapufdli kamapuli 760004",
  "latitude": 19.31124,
  "longitude": 843.7926
}

### get all location
GET   http://localhost:3000/api/admin/get/location/all
Content-Type: application/json


### get my location
GET   http://localhost:3000/api/admin/get/location/my
Content-Type: application/json


### USER

###  login user
POST   http://localhost:3000/api/user/login
Content-Type: application/json

{
  "uid": "9337318873"
}

###  get me
GET    http://localhost:3000/api/admin/me
Content-Type: application/json

### visit location routes
POST   http://localhost:3000/api/user/visit/location
Content-Type: application/json
Cookie: {{{cookie}}}

{
  "locationId": 1,
  "date": "2023-10-01T12:00:00Z",
  "userLatitude": 19.31124,
  "userLongitude": 843.7926
}